# Generated by Django 4.0 on 2022-01-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=122)),
                ('last', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=15)),
                ('location', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
